"""Core data model, PRD section 9.1

Revision ID: 0002
Revises: 0001
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('work_email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('specialisms', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('delegate_id', sa.UUID(), nullable=True),
    sa.Column('workload', sa.Integer(), nullable=False),
    sa.Column('workload_ceiling', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_channel', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delegate_id'], ['app_user.id'], name=op.f('fk_app_user_delegate_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('subject', name=op.f('uq_app_user_subject')),
    sa.UniqueConstraint('work_email', name=op.f('uq_app_user_work_email'))
    )
    op.create_table('approval_chain_definition',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('entity', sa.String(length=3), nullable=True),
    sa.Column('agreement_type', sa.String(length=64), nullable=True),
    sa.Column('risk_tier', sa.String(length=16), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_chain_definition'))
    )
    op.create_table('audit_event',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=False),
    sa.Column('entity', sa.String(length=3), nullable=True),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('previous_digest', sa.String(length=64), nullable=True),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    op.create_index(op.f('ix_audit_event_action'), 'audit_event', ['action'], unique=False)
    op.create_index('ix_audit_event_actor_time', 'audit_event', ['actor_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_event_entity'), 'audit_event', ['entity'], unique=False)
    op.create_index('ix_audit_event_object', 'audit_event', ['object_type', 'object_id'], unique=False)
    op.create_index(op.f('ix_audit_event_occurred_at'), 'audit_event', ['occurred_at'], unique=False)
    op.create_table('counterparty',
    sa.Column('reference', sa.String(length=16), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('trading_names', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('counterparty_type', sa.String(length=64), nullable=False),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('jurisdiction', sa.String(length=64), nullable=False),
    sa.Column('addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relationship_class', sa.String(length=64), nullable=False),
    sa.Column('risk_class', sa.String(length=32), nullable=False),
    sa.Column('negotiation_notes', sa.Text(), nullable=True),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['counterparty.id'], name=op.f('fk_counterparty_merged_into_id_counterparty'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparty'))
    )
    op.create_index(op.f('ix_counterparty_domain'), 'counterparty', ['domain'], unique=False)
    op.create_index(op.f('ix_counterparty_legal_name'), 'counterparty', ['legal_name'], unique=False)
    op.create_index(op.f('ix_counterparty_reference'), 'counterparty', ['reference'], unique=True)
    op.create_index(op.f('ix_counterparty_registration_number'), 'counterparty', ['registration_number'], unique=False)
    op.create_table('egress_log',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connector_code', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('record_reference', sa.String(length=64), nullable=True),
    sa.Column('data_class', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_egress_log'))
    )
    op.create_index(op.f('ix_egress_log_connector_code'), 'egress_log', ['connector_code'], unique=False)
    op.create_index(op.f('ix_egress_log_occurred_at'), 'egress_log', ['occurred_at'], unique=False)
    op.create_table('idempotency_key',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_key')),
    sa.UniqueConstraint('key', 'endpoint', name=op.f('uq_idempotency_key_key'))
    )
    op.create_index(op.f('ix_idempotency_key_key'), 'idempotency_key', ['key'], unique=False)
    op.create_table('kpi_baseline',
    sa.Column('kpi_code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('measurement_method', sa.Text(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('baseline_captured_on', sa.Date(), nullable=True),
    sa.Column('phase_1_target', sa.Float(), nullable=True),
    sa.Column('phase_3_target', sa.Float(), nullable=True),
    sa.Column('target_direction', sa.String(length=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_baseline')),
    sa.UniqueConstraint('kpi_code', name=op.f('uq_kpi_baseline_kpi_code'))
    )
    op.create_table('organisation',
    sa.Column('entity_code', sa.String(length=3), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('default_jurisdiction', sa.String(length=64), nullable=False),
    sa.Column('branding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retention_profile', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation')),
    sa.UniqueConstraint('entity_code', name=op.f('uq_organisation_entity_code'))
    )
    op.create_table('outbox_event',
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_event'))
    )
    op.create_index(op.f('ix_outbox_event_available_at'), 'outbox_event', ['available_at'], unique=False)
    op.create_index(op.f('ix_outbox_event_status'), 'outbox_event', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_event_topic'), 'outbox_event', ['topic'], unique=False)
    op.create_table('playbook',
    sa.Column('agreement_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('required_clauses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playbook')),
    sa.UniqueConstraint('agreement_type', name=op.f('uq_playbook_agreement_type'))
    )
    op.create_table('request_type',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('business_label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agreement_type', sa.String(length=64), nullable=False),
    sa.Column('practice_code', sa.String(length=3), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mandatory_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('value_threshold', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('drafting_enabled', sa.Boolean(), nullable=False),
    sa.Column('tier_1_auto_issue', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_type')),
    sa.UniqueConstraint('code', name=op.f('uq_request_type_code'))
    )
    op.create_table('retention_policy',
    sa.Column('record_class', sa.String(length=64), nullable=False),
    sa.Column('retain_years', sa.Integer(), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('deletion_requires_approval', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_policy')),
    sa.UniqueConstraint('record_class', name=op.f('uq_retention_policy_record_class'))
    )
    op.create_table('capability',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('module', sa.String(length=8), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('max_data_class', sa.String(length=16), nullable=False),
    sa.Column('tier_ceiling', sa.String(length=16), nullable=False),
    sa.Column('human_requirement', sa.Text(), nullable=False),
    sa.Column('confirming_role', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('disabled_for_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('gate_expression', sa.String(length=128), nullable=False),
    sa.Column('gate_threshold', sa.Float(), nullable=True),
    sa.Column('last_score', sa.Float(), nullable=True),
    sa.Column('last_score_label', sa.String(length=64), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('golden_set', sa.String(length=64), nullable=True),
    sa.Column('prompt_reference', sa.String(length=128), nullable=True),
    sa.Column('tools_allowed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], name=op.f('fk_capability_owner_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability'))
    )
    op.create_index(op.f('ix_capability_code'), 'capability', ['code'], unique=True)
    op.create_index(op.f('ix_capability_state'), 'capability', ['state'], unique=False)
    op.create_table('clause',
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('entity_applicability', postgresql.ARRAY(sa.String(length=3)), nullable=False),
    sa.Column('jurisdiction', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('required_for_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], name=op.f('fk_clause_owner_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clause'))
    )
    op.create_index(op.f('ix_clause_category'), 'clause', ['category'], unique=True)
    op.create_table('compliance_item',
    sa.Column('requirement', sa.String(length=255), nullable=False),
    sa.Column('statutory_reference', sa.String(length=128), nullable=True),
    sa.Column('jurisdiction', sa.String(length=64), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('recurrence', sa.String(length=24), nullable=False),
    sa.Column('accountable_owner_id', sa.UUID(), nullable=True),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=512), nullable=True),
    sa.Column('filing_number', sa.String(length=128), nullable=True),
    sa.Column('filed_by_id', sa.UUID(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['accountable_owner_id'], ['app_user.id'], name=op.f('fk_compliance_item_accountable_owner_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['filed_by_id'], ['app_user.id'], name=op.f('fk_compliance_item_filed_by_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['compliance_item.id'], name=op.f('fk_compliance_item_supersedes_id_compliance_item'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_item'))
    )
    op.create_index(op.f('ix_compliance_item_entity'), 'compliance_item', ['entity'], unique=False)
    op.create_index(op.f('ix_compliance_item_next_due_date'), 'compliance_item', ['next_due_date'], unique=False)
    op.create_index(op.f('ix_compliance_item_status'), 'compliance_item', ['status'], unique=False)
    op.create_table('config_setting',
    sa.Column('area', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['app_user.id'], name=op.f('fk_config_setting_changed_by_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_setting')),
    sa.UniqueConstraint('area', 'key', 'version', name=op.f('uq_config_setting_area'))
    )
    op.create_index(op.f('ix_config_setting_area'), 'config_setting', ['area'], unique=False)
    op.create_table('connector',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('permitted_data_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], name=op.f('fk_connector_owner_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector')),
    sa.UniqueConstraint('code', name=op.f('uq_connector_code'))
    )
    op.create_table('mailbox',
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('entity', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], name=op.f('fk_mailbox_owner_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mailbox')),
    sa.UniqueConstraint('address', name=op.f('uq_mailbox_address'))
    )
    op.create_table('product',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('intended_users', sa.Text(), nullable=True),
    sa.Column('datasets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('models', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vendors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_status', sa.String(length=24), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], name=op.f('fk_product_owner_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_index(op.f('ix_product_entity'), 'product', ['entity'], unique=False)
    op.create_table('request',
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('request_type_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('proposed_counterparty', sa.String(length=255), nullable=True),
    sa.Column('counterparty_id', sa.UUID(), nullable=True),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('value_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('value_currency', sa.String(length=3), nullable=False),
    sa.Column('personal_data', sa.Boolean(), nullable=False),
    sa.Column('special_category_data', sa.Boolean(), nullable=False),
    sa.Column('third_party_confidential', sa.Boolean(), nullable=False),
    sa.Column('leaves_nigeria', sa.Boolean(), nullable=False),
    sa.Column('privacy_flag', sa.Boolean(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('triage_notes', sa.Text(), nullable=True),
    sa.Column('suggested_tier', sa.String(length=16), nullable=True),
    sa.Column('tier_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_owner_id', sa.UUID(), nullable=True),
    sa.Column('owner_rationale', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], name=op.f('fk_request_counterparty_id_counterparty'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_type.id'], name=op.f('fk_request_request_type_id_request_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_id'], ['app_user.id'], name=op.f('fk_request_requester_id_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['suggested_owner_id'], ['app_user.id'], name=op.f('fk_request_suggested_owner_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request'))
    )
    op.create_index(op.f('ix_request_entity'), 'request', ['entity'], unique=False)
    op.create_index(op.f('ix_request_privacy_flag'), 'request', ['privacy_flag'], unique=False)
    op.create_index(op.f('ix_request_reference'), 'request', ['reference'], unique=True)
    op.create_index(op.f('ix_request_status'), 'request', ['status'], unique=False)
    op.create_table('template',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agreement_type', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('entity_applicability', postgresql.ARRAY(sa.String(length=3)), nullable=False),
    sa.Column('jurisdiction', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], name=op.f('fk_template_owner_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template'))
    )
    op.create_index(op.f('ix_template_agreement_type'), 'template', ['agreement_type'], unique=False)
    op.create_index(op.f('ix_template_code'), 'template', ['code'], unique=True)
    op.create_table('user_entity',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_code', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['entity_code'], ['organisation.entity_code'], name=op.f('fk_user_entity_entity_code_organisation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_user_entity_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_entity')),
    sa.UniqueConstraint('user_id', 'entity_code', name=op.f('uq_user_entity_user_id'))
    )
    op.create_table('vendor',
    sa.Column('counterparty_id', sa.UUID(), nullable=False),
    sa.Column('service_owner_id', sa.UUID(), nullable=True),
    sa.Column('security_review_status', sa.String(length=32), nullable=False),
    sa.Column('security_review_date', sa.Date(), nullable=True),
    sa.Column('open_security_findings', sa.Integer(), nullable=False),
    sa.Column('data_processing_terms', sa.Text(), nullable=True),
    sa.Column('subprocessors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hosting_locations', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('spend_band', sa.String(length=32), nullable=True),
    sa.Column('performance_notes', sa.Text(), nullable=True),
    sa.Column('assessment_expired', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], name=op.f('fk_vendor_counterparty_id_counterparty'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_owner_id'], ['app_user.id'], name=op.f('fk_vendor_service_owner_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor')),
    sa.UniqueConstraint('counterparty_id', name=op.f('uq_vendor_counterparty_id'))
    )
    op.create_table('attachment',
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('scan_status', sa.String(length=24), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], name=op.f('fk_attachment_request_id_request'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['app_user.id'], name=op.f('fk_attachment_uploaded_by_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment'))
    )
    op.create_table('clause_version',
    sa.Column('clause_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('house_position', sa.Text(), nullable=False),
    sa.Column('fallbacks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unacceptable_position', sa.Text(), nullable=True),
    sa.Column('usage_conditions', sa.Text(), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['app_user.id'], name=op.f('fk_clause_version_approved_by_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clause_id'], ['clause.id'], name=op.f('fk_clause_version_clause_id_clause'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['clause_version.id'], name=op.f('fk_clause_version_supersedes_id_clause_version'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clause_version')),
    sa.UniqueConstraint('clause_id', 'major', 'minor', name=op.f('uq_clause_version_clause_id'))
    )
    op.create_index(op.f('ix_clause_version_reference'), 'clause_version', ['reference'], unique=True)
    op.create_index(op.f('ix_clause_version_review_date'), 'clause_version', ['review_date'], unique=False)
    op.create_index(op.f('ix_clause_version_status'), 'clause_version', ['status'], unique=False)
    op.create_table('evaluation_run',
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('golden_set', sa.String(length=64), nullable=False),
    sa.Column('set_size', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_label', sa.String(length=64), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capability.id'], name=op.f('fk_evaluation_run_capability_id_capability'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_run'))
    )
    op.create_table('matter',
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('request_type_id', sa.UUID(), nullable=True),
    sa.Column('practice_code', sa.String(length=3), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=True),
    sa.Column('requester_id', sa.UUID(), nullable=True),
    sa.Column('business_owner_id', sa.UUID(), nullable=True),
    sa.Column('responsible_lawyer_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('risk_tier', sa.String(length=16), nullable=False),
    sa.Column('tier_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tier_overridden', sa.Boolean(), nullable=False),
    sa.Column('tier_override_reason', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('state_before_hold', sa.String(length=40), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('sla_target_hours', sa.Integer(), nullable=True),
    sa.Column('sla_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocker', sa.String(length=255), nullable=True),
    sa.Column('privacy_flag', sa.Boolean(), nullable=False),
    sa.Column('value_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('value_currency', sa.String(length=3), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('parent_matter_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['business_owner_id'], ['app_user.id'], name=op.f('fk_matter_business_owner_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], name=op.f('fk_matter_counterparty_id_counterparty'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_matter_id'], ['matter.id'], name=op.f('fk_matter_parent_matter_id_matter'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], name=op.f('fk_matter_request_id_request'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_type.id'], name=op.f('fk_matter_request_type_id_request_type'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['app_user.id'], name=op.f('fk_matter_requester_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsible_lawyer_id'], ['app_user.id'], name=op.f('fk_matter_responsible_lawyer_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matter'))
    )
    op.create_index(op.f('ix_matter_counterparty_id'), 'matter', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_matter_entity'), 'matter', ['entity'], unique=False)
    op.create_index(op.f('ix_matter_number'), 'matter', ['number'], unique=True)
    op.create_index(op.f('ix_matter_responsible_lawyer_id'), 'matter', ['responsible_lawyer_id'], unique=False)
    op.create_index(op.f('ix_matter_restricted'), 'matter', ['restricted'], unique=False)
    op.create_index(op.f('ix_matter_risk_tier'), 'matter', ['risk_tier'], unique=False)
    op.create_index(op.f('ix_matter_status'), 'matter', ['status'], unique=False)
    op.create_table('template_version',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clause_references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['app_user.id'], name=op.f('fk_template_version_approved_by_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['template_version.id'], name=op.f('fk_template_version_supersedes_id_template_version'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], name=op.f('fk_template_version_template_id_template'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_version')),
    sa.UniqueConstraint('template_id', 'major', 'minor', name=op.f('uq_template_version_template_id'))
    )
    op.create_index(op.f('ix_template_version_reference'), 'template_version', ['reference'], unique=True)
    op.create_index(op.f('ix_template_version_review_date'), 'template_version', ['review_date'], unique=False)
    op.create_index(op.f('ix_template_version_status'), 'template_version', ['status'], unique=False)
    op.create_table('ai_interaction',
    sa.Column('interaction_id', sa.String(length=64), nullable=False),
    sa.Column('capability_code', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=3), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('prompt_reference', sa.String(length=128), nullable=True),
    sa.Column('input_digest', sa.String(length=64), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('data_class', sa.String(length=16), nullable=False),
    sa.Column('retrieved_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_reference', sa.String(length=128), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unsupported_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('permitted_data_class', sa.String(length=16), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('required_role', sa.String(length=32), nullable=True),
    sa.Column('human_decision', sa.String(length=16), nullable=False),
    sa.Column('correction_detail', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shadow', sa.Boolean(), nullable=False),
    sa.Column('injection_detected', sa.Boolean(), nullable=False),
    sa.Column('refused', sa.Boolean(), nullable=False),
    sa.Column('refusal_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['app_user.id'], name=op.f('fk_ai_interaction_decided_by_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_ai_interaction_matter_id_matter'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_ai_interaction_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_interaction'))
    )
    op.create_index(op.f('ix_ai_interaction_capability_code'), 'ai_interaction', ['capability_code'], unique=False)
    op.create_index(op.f('ix_ai_interaction_entity'), 'ai_interaction', ['entity'], unique=False)
    op.create_index(op.f('ix_ai_interaction_human_decision'), 'ai_interaction', ['human_decision'], unique=False)
    op.create_index(op.f('ix_ai_interaction_injection_detected'), 'ai_interaction', ['injection_detected'], unique=False)
    op.create_index(op.f('ix_ai_interaction_interaction_id'), 'ai_interaction', ['interaction_id'], unique=True)
    op.create_index(op.f('ix_ai_interaction_matter_id'), 'ai_interaction', ['matter_id'], unique=False)
    op.create_index(op.f('ix_ai_interaction_shadow'), 'ai_interaction', ['shadow'], unique=False)
    op.create_table('communication',
    sa.Column('mailbox_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_corrected', sa.Boolean(), nullable=False),
    sa.Column('corrected_classification', sa.String(length=32), nullable=True),
    sa.Column('implied_work', sa.Boolean(), nullable=False),
    sa.Column('implied_work_phrase', sa.Text(), nullable=True),
    sa.Column('awaiting_response_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('proposed_acknowledgment', sa.Text(), nullable=True),
    sa.Column('proposed_matter_type', sa.String(length=64), nullable=True),
    sa.Column('proposed_priority', sa.String(length=16), nullable=True),
    sa.Column('proposed_owner_id', sa.UUID(), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('classification_interaction_id', sa.String(length=64), nullable=True),
    sa.Column('injection_flagged', sa.Boolean(), nullable=False),
    sa.Column('quarantined', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailbox.id'], name=op.f('fk_communication_mailbox_id_mailbox'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_communication_matter_id_matter'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_owner_id'], ['app_user.id'], name=op.f('fk_communication_proposed_owner_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication')),
    sa.UniqueConstraint('external_id', name=op.f('uq_communication_external_id'))
    )
    op.create_index(op.f('ix_communication_classification'), 'communication', ['classification'], unique=False)
    op.create_index(op.f('ix_communication_entity'), 'communication', ['entity'], unique=False)
    op.create_index(op.f('ix_communication_handled'), 'communication', ['handled'], unique=False)
    op.create_index(op.f('ix_communication_implied_work'), 'communication', ['implied_work'], unique=False)
    op.create_index(op.f('ix_communication_matter_id'), 'communication', ['matter_id'], unique=False)
    op.create_index(op.f('ix_communication_received_at'), 'communication', ['received_at'], unique=False)
    op.create_table('contract',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=True),
    sa.Column('agreement_type', sa.String(length=64), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('renewal_type', sa.String(length=32), nullable=False),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('value_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('value_currency', sa.String(length=3), nullable=False),
    sa.Column('governing_law', sa.String(length=64), nullable=False),
    sa.Column('signature_status', sa.String(length=32), nullable=False),
    sa.Column('executed_document_id', sa.UUID(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('signature_certificate', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('executed_outside_platform', sa.Boolean(), nullable=False),
    sa.Column('execution_reason', sa.Text(), nullable=True),
    sa.Column('amends_contract_id', sa.UUID(), nullable=True),
    sa.Column('authoritative', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['amends_contract_id'], ['contract.id'], name=op.f('fk_contract_amends_contract_id_contract'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], name=op.f('fk_contract_counterparty_id_counterparty'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['executed_document_id'], ['document.id'], name=op.f('fk_contract_executed_document_id_document'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_contract_matter_id_matter'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract'))
    )
    op.create_index(op.f('ix_contract_agreement_type'), 'contract', ['agreement_type'], unique=False)
    op.create_index(op.f('ix_contract_content_hash'), 'contract', ['content_hash'], unique=False)
    op.create_index(op.f('ix_contract_counterparty_id'), 'contract', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_contract_end_date'), 'contract', ['end_date'], unique=False)
    op.create_index(op.f('ix_contract_entity'), 'contract', ['entity'], unique=False)
    op.create_index(op.f('ix_contract_matter_id'), 'contract', ['matter_id'], unique=False)
    op.create_index(op.f('ix_contract_reference'), 'contract', ['reference'], unique=True)
    op.create_table('decision_record',
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('clause_id', sa.UUID(), nullable=True),
    sa.Column('entity', sa.String(length=3), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('alternatives_considered', sa.Text(), nullable=True),
    sa.Column('clause_references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('authority_level', sa.String(length=24), nullable=False),
    sa.Column('residual_risk_accepted', sa.Boolean(), nullable=False),
    sa.Column('commercial_rationale', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('counterparty_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clause.id'], name=op.f('fk_decision_record_clause_id_clause'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], name=op.f('fk_decision_record_counterparty_id_counterparty'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['app_user.id'], name=op.f('fk_decision_record_decided_by_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_decision_record_matter_id_matter'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['decision_record.id'], name=op.f('fk_decision_record_superseded_by_id_decision_record'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_record'))
    )
    op.create_index(op.f('ix_decision_record_entity'), 'decision_record', ['entity'], unique=False)
    op.create_index(op.f('ix_decision_record_matter_id'), 'decision_record', ['matter_id'], unique=False)
    op.create_index(op.f('ix_decision_record_sequence'), 'decision_record', ['sequence'], unique=False)
    op.create_table('matter_access',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['app_user.id'], name=op.f('fk_matter_access_granted_by_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_matter_access_matter_id_matter'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_matter_access_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matter_access')),
    sa.UniqueConstraint('matter_id', 'user_id', name=op.f('uq_matter_access_matter_id'))
    )
    op.create_table('matter_link',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('linked_matter_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['linked_matter_id'], ['matter.id'], name=op.f('fk_matter_link_linked_matter_id_matter'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_matter_link_matter_id_matter'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matter_link')),
    sa.UniqueConstraint('matter_id', 'linked_matter_id', 'link_type', name=op.f('uq_matter_link_matter_id'))
    )
    op.create_table('matter_transition',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.String(length=40), nullable=True),
    sa.Column('to_state', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invalidated_approvals', sa.Integer(), nullable=False),
    sa.Column('clock_running', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], name=op.f('fk_matter_transition_actor_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_matter_transition_matter_id_matter'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matter_transition'))
    )
    op.create_index('ix_matter_transition_matter_time', 'matter_transition', ['matter_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_matter_transition_occurred_at'), 'matter_transition', ['occurred_at'], unique=False)
    op.create_table('memory_chunk',
    sa.Column('entity', sa.String(length=3), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.String(length=64), nullable=False),
    sa.Column('source_detail', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('current_replacement', sa.String(length=64), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_memory_chunk_matter_id_matter'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_chunk'))
    )
    op.create_index(op.f('ix_memory_chunk_entity'), 'memory_chunk', ['entity'], unique=False)
    op.create_index('ix_memory_chunk_scope', 'memory_chunk', ['entity', 'restricted'], unique=False)
    op.create_index('ix_memory_chunk_source', 'memory_chunk', ['source_type', 'source_reference'], unique=False)
    op.create_index(op.f('ix_memory_chunk_source_type'), 'memory_chunk', ['source_type'], unique=False)
    op.create_table('assessment',
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('assessment_type', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('stage_records', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('controls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('testing_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('residual_risk_decision', sa.String(length=24), nullable=True),
    sa.Column('residual_risk_reason', sa.Text(), nullable=True),
    sa.Column('residual_risk_owner_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('reassessment_triggered', sa.Boolean(), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_assessment_contract_id_contract'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_assessment_matter_id_matter'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_assessment_product_id_product'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['residual_risk_owner_id'], ['app_user.id'], name=op.f('fk_assessment_residual_risk_owner_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], name=op.f('fk_assessment_vendor_id_vendor'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment'))
    )
    op.create_index(op.f('ix_assessment_entity'), 'assessment', ['entity'], unique=False)
    op.create_index(op.f('ix_assessment_reference'), 'assessment', ['reference'], unique=True)
    op.create_index(op.f('ix_assessment_review_date'), 'assessment', ['review_date'], unique=False)
    op.create_index(op.f('ix_assessment_stage'), 'assessment', ['stage'], unique=False)
    op.create_table('document',
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template_version_ref', sa.String(length=40), nullable=True),
    sa.Column('clause_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('generated_by_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('novel_clause_count', sa.Integer(), nullable=False),
    sa.Column('open_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('style_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consistency_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_document_contract_id_contract'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['app_user.id'], name=op.f('fk_document_generated_by_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_document_matter_id_matter'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['document.id'], name=op.f('fk_document_supersedes_id_document'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_content_hash'), 'document', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_entity'), 'document', ['entity'], unique=False)
    op.create_index(op.f('ix_document_matter_id'), 'document', ['matter_id'], unique=False)
    op.create_table('approval',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_definition_id', sa.UUID(), nullable=True),
    sa.Column('chain_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=128), nullable=False),
    sa.Column('step_mode', sa.String(length=16), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('approver_role', sa.String(length=32), nullable=True),
    sa.Column('delegate_used_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminders_sent', sa.Integer(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_by_event', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['app_user.id'], name=op.f('fk_approval_approver_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chain_definition_id'], ['approval_chain_definition.id'], name=op.f('fk_approval_chain_definition_id_approval_chain_definition'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_approval_contract_id_contract'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delegate_used_id'], ['app_user.id'], name=op.f('fk_approval_delegate_used_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_approval_document_id_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_approval_matter_id_matter'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval'))
    )
    op.create_index(op.f('ix_approval_approver_id'), 'approval', ['approver_id'], unique=False)
    op.create_index(op.f('ix_approval_decision'), 'approval', ['decision'], unique=False)
    op.create_index(op.f('ix_approval_document_hash'), 'approval', ['document_hash'], unique=False)
    op.create_index(op.f('ix_approval_matter_id'), 'approval', ['matter_id'], unique=False)
    op.create_table('extracted_value',
    sa.Column('communication_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source_sentence', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communication.id'], name=op.f('fk_extracted_value_communication_id_communication'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['app_user.id'], name=op.f('fk_extracted_value_decided_by_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_extracted_value_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_value'))
    )
    op.create_index(op.f('ix_extracted_value_communication_id'), 'extracted_value', ['communication_id'], unique=False)
    op.create_table('obligation',
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('compliance_item_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('obligation_type', sa.String(length=32), nullable=False),
    sa.Column('source_clause', sa.String(length=64), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('recurrence', sa.String(length=24), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('escalation_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=512), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.UUID(), nullable=True),
    sa.Column('decision_options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_taken', sa.String(length=32), nullable=True),
    sa.Column('interaction_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name=op.f('fk_obligation_assessment_id_assessment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['app_user.id'], name=op.f('fk_obligation_completed_by_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['compliance_item_id'], ['compliance_item.id'], name=op.f('fk_obligation_compliance_item_id_compliance_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_obligation_contract_id_contract'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_obligation_matter_id_matter'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], name=op.f('fk_obligation_owner_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obligation'))
    )
    op.create_index(op.f('ix_obligation_contract_id'), 'obligation', ['contract_id'], unique=False)
    op.create_index(op.f('ix_obligation_due_date'), 'obligation', ['due_date'], unique=False)
    op.create_index(op.f('ix_obligation_entity'), 'obligation', ['entity'], unique=False)
    op.create_index(op.f('ix_obligation_owner_id'), 'obligation', ['owner_id'], unique=False)
    op.create_index(op.f('ix_obligation_reference'), 'obligation', ['reference'], unique=True)
    op.create_index(op.f('ix_obligation_status'), 'obligation', ['status'], unique=False)
    op.create_table('review_finding',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('their_reference', sa.String(length=64), nullable=True),
    sa.Column('clause_absent', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('clause_category', sa.String(length=16), nullable=True),
    sa.Column('clause_version_ref', sa.String(length=32), nullable=True),
    sa.Column('their_text', sa.Text(), nullable=True),
    sa.Column('house_position', sa.Text(), nullable=True),
    sa.Column('suggested_redline', sa.Text(), nullable=True),
    sa.Column('required_authority', sa.String(length=24), nullable=False),
    sa.Column('matches_preapproved_fallback', sa.Boolean(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clearance_rule', sa.Text(), nullable=True),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('interaction_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['app_user.id'], name=op.f('fk_review_finding_decided_by_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_review_finding_document_id_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_review_finding_matter_id_matter'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_finding'))
    )
    op.create_index(op.f('ix_review_finding_decision'), 'review_finding', ['decision'], unique=False)
    op.create_index(op.f('ix_review_finding_matter_id'), 'review_finding', ['matter_id'], unique=False)
    op.create_index(op.f('ix_review_finding_severity'), 'review_finding', ['severity'], unique=False)
    op.create_table('signature_request',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_reference', sa.String(length=128), nullable=True),
    sa.Column('signers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audit_certificate', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_signature_request_contract_id_contract'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_signature_request_document_id_document'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.id'], name=op.f('fk_signature_request_matter_id_matter'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['app_user.id'], name=op.f('fk_signature_request_requested_by_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signature_request'))
    )
    op.create_index(op.f('ix_signature_request_external_reference'), 'signature_request', ['external_reference'], unique=False)
    op.create_index(op.f('ix_signature_request_status'), 'signature_request', ['status'], unique=False)
    op.create_table('suggestion',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('block_key', sa.String(length=64), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('proposed_text', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=64), nullable=True),
    sa.Column('novel', sa.Boolean(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interaction_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['app_user.id'], name=op.f('fk_suggestion_decided_by_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_suggestion_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestion'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestion')
    op.drop_index(op.f('ix_signature_request_status'), table_name='signature_request')
    op.drop_index(op.f('ix_signature_request_external_reference'), table_name='signature_request')
    op.drop_table('signature_request')
    op.drop_index(op.f('ix_review_finding_severity'), table_name='review_finding')
    op.drop_index(op.f('ix_review_finding_matter_id'), table_name='review_finding')
    op.drop_index(op.f('ix_review_finding_decision'), table_name='review_finding')
    op.drop_table('review_finding')
    op.drop_index(op.f('ix_obligation_status'), table_name='obligation')
    op.drop_index(op.f('ix_obligation_reference'), table_name='obligation')
    op.drop_index(op.f('ix_obligation_owner_id'), table_name='obligation')
    op.drop_index(op.f('ix_obligation_entity'), table_name='obligation')
    op.drop_index(op.f('ix_obligation_due_date'), table_name='obligation')
    op.drop_index(op.f('ix_obligation_contract_id'), table_name='obligation')
    op.drop_table('obligation')
    op.drop_index(op.f('ix_extracted_value_communication_id'), table_name='extracted_value')
    op.drop_table('extracted_value')
    op.drop_index(op.f('ix_approval_matter_id'), table_name='approval')
    op.drop_index(op.f('ix_approval_document_hash'), table_name='approval')
    op.drop_index(op.f('ix_approval_decision'), table_name='approval')
    op.drop_index(op.f('ix_approval_approver_id'), table_name='approval')
    op.drop_table('approval')
    op.drop_index(op.f('ix_document_matter_id'), table_name='document')
    op.drop_index(op.f('ix_document_entity'), table_name='document')
    op.drop_index(op.f('ix_document_content_hash'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_assessment_stage'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_review_date'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_reference'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_entity'), table_name='assessment')
    op.drop_table('assessment')
    op.drop_index(op.f('ix_memory_chunk_source_type'), table_name='memory_chunk')
    op.drop_index('ix_memory_chunk_source', table_name='memory_chunk')
    op.drop_index('ix_memory_chunk_scope', table_name='memory_chunk')
    op.drop_index(op.f('ix_memory_chunk_entity'), table_name='memory_chunk')
    op.drop_table('memory_chunk')
    op.drop_index(op.f('ix_matter_transition_occurred_at'), table_name='matter_transition')
    op.drop_index('ix_matter_transition_matter_time', table_name='matter_transition')
    op.drop_table('matter_transition')
    op.drop_table('matter_link')
    op.drop_table('matter_access')
    op.drop_index(op.f('ix_decision_record_sequence'), table_name='decision_record')
    op.drop_index(op.f('ix_decision_record_matter_id'), table_name='decision_record')
    op.drop_index(op.f('ix_decision_record_entity'), table_name='decision_record')
    op.drop_table('decision_record')
    op.drop_index(op.f('ix_contract_reference'), table_name='contract')
    op.drop_index(op.f('ix_contract_matter_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_entity'), table_name='contract')
    op.drop_index(op.f('ix_contract_end_date'), table_name='contract')
    op.drop_index(op.f('ix_contract_counterparty_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_content_hash'), table_name='contract')
    op.drop_index(op.f('ix_contract_agreement_type'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_communication_received_at'), table_name='communication')
    op.drop_index(op.f('ix_communication_matter_id'), table_name='communication')
    op.drop_index(op.f('ix_communication_implied_work'), table_name='communication')
    op.drop_index(op.f('ix_communication_handled'), table_name='communication')
    op.drop_index(op.f('ix_communication_entity'), table_name='communication')
    op.drop_index(op.f('ix_communication_classification'), table_name='communication')
    op.drop_table('communication')
    op.drop_index(op.f('ix_ai_interaction_shadow'), table_name='ai_interaction')
    op.drop_index(op.f('ix_ai_interaction_matter_id'), table_name='ai_interaction')
    op.drop_index(op.f('ix_ai_interaction_interaction_id'), table_name='ai_interaction')
    op.drop_index(op.f('ix_ai_interaction_injection_detected'), table_name='ai_interaction')
    op.drop_index(op.f('ix_ai_interaction_human_decision'), table_name='ai_interaction')
    op.drop_index(op.f('ix_ai_interaction_entity'), table_name='ai_interaction')
    op.drop_index(op.f('ix_ai_interaction_capability_code'), table_name='ai_interaction')
    op.drop_table('ai_interaction')
    op.drop_index(op.f('ix_template_version_status'), table_name='template_version')
    op.drop_index(op.f('ix_template_version_review_date'), table_name='template_version')
    op.drop_index(op.f('ix_template_version_reference'), table_name='template_version')
    op.drop_table('template_version')
    op.drop_index(op.f('ix_matter_status'), table_name='matter')
    op.drop_index(op.f('ix_matter_risk_tier'), table_name='matter')
    op.drop_index(op.f('ix_matter_restricted'), table_name='matter')
    op.drop_index(op.f('ix_matter_responsible_lawyer_id'), table_name='matter')
    op.drop_index(op.f('ix_matter_number'), table_name='matter')
    op.drop_index(op.f('ix_matter_entity'), table_name='matter')
    op.drop_index(op.f('ix_matter_counterparty_id'), table_name='matter')
    op.drop_table('matter')
    op.drop_table('evaluation_run')
    op.drop_index(op.f('ix_clause_version_status'), table_name='clause_version')
    op.drop_index(op.f('ix_clause_version_review_date'), table_name='clause_version')
    op.drop_index(op.f('ix_clause_version_reference'), table_name='clause_version')
    op.drop_table('clause_version')
    op.drop_table('attachment')
    op.drop_table('vendor')
    op.drop_table('user_entity')
    op.drop_index(op.f('ix_template_code'), table_name='template')
    op.drop_index(op.f('ix_template_agreement_type'), table_name='template')
    op.drop_table('template')
    op.drop_index(op.f('ix_request_status'), table_name='request')
    op.drop_index(op.f('ix_request_reference'), table_name='request')
    op.drop_index(op.f('ix_request_privacy_flag'), table_name='request')
    op.drop_index(op.f('ix_request_entity'), table_name='request')
    op.drop_table('request')
    op.drop_index(op.f('ix_product_entity'), table_name='product')
    op.drop_table('product')
    op.drop_table('mailbox')
    op.drop_table('connector')
    op.drop_index(op.f('ix_config_setting_area'), table_name='config_setting')
    op.drop_table('config_setting')
    op.drop_index(op.f('ix_compliance_item_status'), table_name='compliance_item')
    op.drop_index(op.f('ix_compliance_item_next_due_date'), table_name='compliance_item')
    op.drop_index(op.f('ix_compliance_item_entity'), table_name='compliance_item')
    op.drop_table('compliance_item')
    op.drop_index(op.f('ix_clause_category'), table_name='clause')
    op.drop_table('clause')
    op.drop_index(op.f('ix_capability_state'), table_name='capability')
    op.drop_index(op.f('ix_capability_code'), table_name='capability')
    op.drop_table('capability')
    op.drop_table('retention_policy')
    op.drop_table('request_type')
    op.drop_table('playbook')
    op.drop_index(op.f('ix_outbox_event_topic'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_status'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_available_at'), table_name='outbox_event')
    op.drop_table('outbox_event')
    op.drop_table('organisation')
    op.drop_table('kpi_baseline')
    op.drop_index(op.f('ix_idempotency_key_key'), table_name='idempotency_key')
    op.drop_table('idempotency_key')
    op.drop_index(op.f('ix_egress_log_occurred_at'), table_name='egress_log')
    op.drop_index(op.f('ix_egress_log_connector_code'), table_name='egress_log')
    op.drop_table('egress_log')
    op.drop_index(op.f('ix_counterparty_registration_number'), table_name='counterparty')
    op.drop_index(op.f('ix_counterparty_reference'), table_name='counterparty')
    op.drop_index(op.f('ix_counterparty_legal_name'), table_name='counterparty')
    op.drop_index(op.f('ix_counterparty_domain'), table_name='counterparty')
    op.drop_table('counterparty')
    op.drop_index(op.f('ix_audit_event_occurred_at'), table_name='audit_event')
    op.drop_index('ix_audit_event_object', table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_entity'), table_name='audit_event')
    op.drop_index('ix_audit_event_actor_time', table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_action'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_table('approval_chain_definition')
    op.drop_table('app_user')
    # ### end Alembic commands ###
